---
# Source: fortigate-exporter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fortigate-exporter
  labels:
    helm.sh/chart: fortigate-exporter-0.3.0
    app.kubernetes.io/name: fortigate-exporter
    app.kubernetes.io/instance: fortigate-exporter
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9710
      targetPort: metrics
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: fortigate-exporter
    app.kubernetes.io/instance: fortigate-exporter
---
# Source: fortigate-exporter/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortigate-exporter
  labels:
    helm.sh/chart: fortigate-exporter-0.3.0
    app.kubernetes.io/name: fortigate-exporter
    app.kubernetes.io/instance: fortigate-exporter
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fortigate-exporter
      app.kubernetes.io/instance: fortigate-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fortigate-exporter
        app.kubernetes.io/instance: fortigate-exporter
    spec:
      containers:
        - name: fortigate-exporter
          image: "ghcr.io/gopaytech/fortigate_exporter:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9710
              name: metrics
          volumeMounts:
            - mountPath: "/config"
              name: config
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: fortigate-config
---
# Source: fortigate-exporter/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "fortigate-exporter-test-connection"
  labels:
    helm.sh/chart: fortigate-exporter-0.3.0
    app.kubernetes.io/name: fortigate-exporter
    app.kubernetes.io/instance: fortigate-exporter
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['fortigate-exporter:9710']
  restartPolicy: Never
