apiVersion: v1
entries:
  fortigate-exporter:
  - apiVersion: v2
    appVersion: latest
    created: "2025-08-15T10:27:29.313908+05:30"
    description: A Helm chart for Prometheus Fortigate Exporter
    digest: f1f3ce95b2c8c4bb17ab0e2d8f7d83d3ddaa896cd14d1424c478c5d9ab0d42a8
    name: fortigate-exporter
    type: application
    urls:
    - fortigate-exporter-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: latest
    created: "2025-08-15T10:27:29.313389+05:30"
    description: A Helm chart for Prometheus Fortigate Exporter
    digest: f1e2cc1aa71df32611c543f8a43486989c42eb50dbe9fb6d48ca84eb694fae07
    name: fortigate-exporter
    type: application
    urls:
    - fortigate-exporter-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: latest
    created: "2025-08-15T10:27:29.312931+05:30"
    description: A Helm chart for Prometheus Fortigate Exporter
    digest: dd26a7f1bcb34bfd3e3310db351a6409d9489b3aedae671e3542257e816643fd
    name: fortigate-exporter
    type: application
    urls:
    - fortigate-exporter-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: latest
    created: "2025-08-15T10:27:29.312585+05:30"
    description: A Helm chart for Prometheus Fortigate Exporter
    digest: 68e47e75bcd02afe91b0130b26a984fc2b93db4d45d3f1400a5f95c5ff83fa80
    name: fortigate-exporter
    type: application
    urls:
    - fortigate-exporter-0.1.0.tgz
    version: 0.1.0
generated: "2025-08-15T10:27:29.311482+05:30"
